//OBJECT & ARRAY LIBRARIES
let traitObj = {
    "Positive": [
        'Accessible',
        'Active',
        'Adaptable',
        'Admirable',
        'Adventurous',
        'Agreeable',
        'Alert',
        'Allocentric',
        'Amiable',
        'Anticipative',
        'Appreciative',
        'Articulate',
        'Aspiring',
        'Athletic',
        'Attractive',
        'Balanced',
        'Benevolent',
        'Brilliant',
        'Calm',
        'Capable',
        'Captivating',
        'Caring',
        'Challenging',
        'Charismatic',
        'Charming',
        'Cheerful',
        'Clean',
        'Clear-headed',
        'Clever',
        'Colorful',
        'Companionly',
        'Compassionate',
        'Conciliatory',
        'Confident',
        'Conscientious',
        'Considerate',
        'Constant',
        'Contemplative',
        'Cooperative',
        'Courageous',
        'Courteous',
        'Creative',
        'Cultured',
        'Curious',
        'Daring',
        'Debonair',
        'Decent',
        'Decisive',
        'Dedicated',
        'Deep',
        'Dignified',
        'Directed',
        'Disciplined',
        'Discreet',
        'Dramatic',
        'Dutiful',
        'Dynamic',
        'Earnest',
        'Ebullient',
        'Educated',
        'Efficient',
        'Elegant',
        'Eloquent',
        'Empathetic',
        'Energetic',
        'Enthusiastic',
        'Esthetic',
        'Exciting',
        'Extraordinary',
        'Fair',
        'Faithful',
        'Farsighted',
        'Felicific',
        'Firm',
        'Flexible',
        'Focused',
        'Forceful',
        'Forgiving',
        'Forthright',
        'Freethinking',
        'Friendly',
        'Fun-loving',
        'Gallant',
        'Generous',
        'Gentle',
        'Genuine',
        'Good-natured',
        'Gracious',
        'Hardworking',
        'Healthy',
        'Hearty',
        'Helpful',
        'Herioc',
        'High-minded',
        'Honest',
        'Honorable',
        'Humble',
        'Humorous',
        'Idealistic',
        'Imaginative',
        'Impressive',
        'Incisive',
        'Incorruptible',
        'Independent',
        'Individualistic',
        'Innovative',
        'Inoffensive',
        'Insightful',
        'Insouciant',
        'Intelligent',
        'Intuitive',
        'Invulnerable',
        'Kind',
        'Knowledge',
        'Leaderly',
        'Leisurely',
        'Liberal',
        'Logical',
        'Lovable',
        'Loyal',
        'Lyrical',
        'Magnanimous',
        'Many-sided',
        'Masculine',
        'Mature',
        'Methodical',
        'Maticulous',
        'Moderate',
        'Modest',
        'Multi-leveled',
        'Neat',
        'Nonauthoritarian',
        'Objective',
        'Observant',
        'Open',
        'Optimistic',
        'Orderly',
        'Organized',
        'Original',
        'Painstaking',
        'Passionate',
        'Patient',
        'Patriotic',
        'Peaceful',
        'Perceptive',
        'Perfectionist',
        'Personable',
        'Persuasive',
        'Planful',
        'Playful',
        'Polished',
        'Popular',
        'Practical',
        'Precise',
        'Principled',
        'Profound',
        'Protean',
        'Protective',
        'Providential',
        'Prudent',
        'Punctual',
        'Purposeful',
        'Rational',
        'Realistic',
        'Reflective',
        'Relaxed',
        'Reliable',
        'Resourceful',
        'Respectful',
        'Responsible',
        'Responsive',
        'Reverential',
        'Romantic',
        'Rustic',
        'Sage',
        'Sane',
        'Scholarly',
        'Scrupulous',
        'Secure',
        'Selfless',
        'Self-critical',
        'Self-defacing',
        'Self-denying',
        'Self-reliant',
        'Self-sufficent',
        'Sensitive',
        'Sentimental',
        'Seraphic',
        'Serious',
        'Sexy',
        'Sharing',
        'Shrewd',
        'Simple',
        'Skillful',
        'Sober',
        'Sociable',
        'Solid',
        'Sophisticated',
        'Spontaneous',
        'Sporting',
        'Stable',
        'Steadfast',
        'Steady',
        'Stoic',
        'Strong',
        'Studious',
        'Suave',
        'Subtle',
        'Sweet',
        'Sympathetic',
        'Systematic',
        'Tasteful',
        'Teacherly',
        'Thorough',
        'Tidy',
        'Tolerant',
        'Tractable',
        'Trusting',
        'Uncomplaining',
        'Understanding',
        'Undogmatic',
        'Unfoolable',
        'Upright',
        'Urbane',
        'Venturesome',
        'Vivacious',
        'Warm',
        'Well-bred',
        'Well-read',
        'Well-rounded',
        'Winning',
        'Wise',
        'Witty',
        'Youthful'
        ],
    "Neutral": [
        "Absentminded",
        "Aggressive",
        "Ambitious",
        "Amusing",
        "Artful",
        'Ascetic',
        'Authoritarian',
        'Big-thinking',
        'Boyish',
        'Breezy',
        'Businesslike',
        'Busy',
        'Casual',
        'Crebral',
        'Chummy',
        'Circumspect',
        'Competitive',
        'Complex',
        'Confidential',
        'Conservative',
        'Contradictory',
        'Crisp',
        'Cute',
        'Deceptive',
        'Determined',
        'Dominating',
        'Dreamy',
        'Driving',
        'Droll',
        'Dry',
        'Earthy',
        'Effeminate',
        'Emotional',
        'Enigmatic',
        'Experimental',
        'Familial',
        'Folksy',
        'Formal',
        'Freewheeling',
        'Frugal',
        'Glamorous',
        'Guileless',
        'High-spirited',
        'Huried',
        'Hypnotic',
        'Iconoclastic',
        'Idiosyncratic',
        'Impassive',
        'Impersonal',
        'Impressionable',
        'Intense',
        'Invisible',
        'Irreligious',
        'Irreverent',
        'Maternal',
        'Mellow',
        'Modern',
        'Moralistic',
        'Mystical',
        'Neutral',
        'Noncommittal',
        'Noncompetitive',
        'Obedient',
        'Old-fashined',
        'Ordinary',
        'Outspoken',
        'Paternalistic',
        'Physical',
        'Placid',
        'Political',
        'Predictable',
        'Preoccupied',
        'Private',
        'Progressive',
        'Proud',
        'Pure',
        'Questioning',
        'Quiet',
        'Religious',
        'Reserved',
        'Restrained',
        'Retiring',
        'Sarcastic',
        'Self-conscious',
        'Sensual',
        'Skeptical',
        'Smooth',
        'Soft',
        'Solemn',
        'Solitary',
        'Stern',
        'Stoic',
        'Strict',
        'Stubborn',
        'Stylish',
        'Subjective',
        'Surprising',
        'Soft',
        'Tough',
        'Unaggressive',
        'Unambitious',
        'Unceremonious',
        'Unchanging',
        'Undemanding',
        'Unfathomable',
        'Unhurried',
        'Uninhibited',
        'Unpatriotic',
        'Unpredicatable',
        'Unreligious',
        'Unsentimental',
        'Whimsical'
        ],
    "Negative": [
        'Abrasive',
        'Abrupt',
        'Agonizing',
        'Aimless',
        'Airy',
        'Aloof',
        'Amoral',
        'Angry',
        'Anxious',
        'Apathetic',
        'Arbitrary',
        'Argumentative',
        'Arrogant',
        'Artificial',
        'Asocial',
        'Assertive',
        'Astigmatic',
        'Barbaric',
        'Bewildered',
        'Bizarre',
        'Bland',
        'Blunt',
        'Biosterous',
        'Brittle',
        'Brutal',
        'Calculating',
        'Callous',
        'Cantakerous',
        'Careless',
        'Cautious',
        'Charmless',
        'Childish',
        'Clumsy',
        'Coarse',
        'Cold',
        'Colorless',
        'Complacent',
        'Complaintive',
        'Compulsive',
        'Conceited',
        'Condemnatory',
        'Conformist',
        'Confused',
        'Contemptible',
        'Conventional',
        'Cowardly',
        'Crafty',
        'Crass',
        'Crazy',
        'Criminal',
        'Critical',
        'Crude',
        'Cruel',
        'Cynical',
        'Decadent',
        'Deceitful',
        'Delicate',
        'Demanding',
        'Dependent',
        'Desperate',
        'Destructive',
        'Devious',
        'Difficult',
        'Dirty',
        'Disconcerting',
        'Discontented',
        'Discouraging',
        'Discourteous',
        'Dishonest',
        'Disloyal',
        'Disobedient',
        'Disorderly',
        'Disorganized',
        'Disputatious',
        'Disrespectful',
        'Disruptive',
        'Dissolute',
        'Dissonant',
        'Distractible',
        'Disturbing',
        'Dogmatic',
        'Domineering',
        'Dull',
        'Easily Discouraged',
        'Egocentric',
        'Enervated',
        'Envious',
        'Erratic',
        'Escapist',
        'Excitable',
        'Expedient',
        'Extravagant',
        'Extreme',
        'Faithless',
        'False',
        'Fanatical',
        'Fanciful',
        'Fatalistic',
        'Fawning',
        'Fearful',
        'Fickle',
        'Fiery',
        'Fixed',
        'Flamboyant',
        'Foolish',
        'Forgetful',
        'Fraudulent',
        'Frightening',
        'Frivolous',
        'Gloomy',
        'Graceless',
        'Grand',
        'Greedy',
        'Grim',
        'Gullible',
        'Hateful',
        'Haughty',
        'Hedonistic',
        'Hesitant',
        'Hidebound',
        'High-handed',
        'Hostile',
        'Ignorant',
        'Imitative',
        'Impatient',
        'Impractical',
        'Imprudent',
        'Impulsive',
        'Inconsiderate',
        'Incurious',
        'Indecisive',
        'Indulgent',
        'Inert',
        'Inhibited',
        'Insecure',
        'Insensitive',
        'Insincere',
        'Insulting',
        'Intolerant',
        'Irascible',
        'Irrational',
        'Irresponsible',
        'Irritable',
        'Lazy',
        'Libidinous',
        'Loquacious',
        'Malicious',
        'Mannered',
        'Mannerless',
        'Mawkish',
        'Mealymouthed',
        'Mechanical',
        'Meddlesome',
        'Melancholic',
        'Meretricious',
        'Messy',
        'Miserable',
        'Miserly',
        'Misguided',
        'Mistaken',
        'Money-minded',
        'Monstrous',
        'Moody',
        'Morbid',
        'Muddle-headed',
        'Naive',
        'Narcissistic',
        'Narrow',
        'Narrow-minded',
        'Natty',
        'Negativistic',
        'Neglectful',
        'Neurotic',
        'Nihilistic',
        'Obnoxious',
        'Obsessive',
        'Obvious',
        'Odd',
        'Offhand',
        'One-dimensional',
        'One-sided',
        'Opinionated',
        'Opportunistic',
        'Oppressed',
        'Outrageous',
        'Overimaginative',
        'Paranoid',
        'Passive',
        'Pedantic',
        'Perverse',
        'Petty',
        'Pharissical',
        'Phlegmatic',
        'Plodding',
        'Pompous',
        'Possessive',
        'Power-hungry',
        'Predatory',
        'Prejudiced',
        'Presumptuous',
        'Pretentious',
        'Prim',
        'Procrastinating',
        'Profligate',
        'Provocative',
        'Pugnacious',
        'Puritanical',
        'Quirky',
        'Reactionary',
        'Reactive',
        'Regimental',
        'Regretful',
        'Repentant',
        'Repressed',
        'Resentful',
        'Ridiculous',
        'Rigid',
        'Ritualistic',
        'Rowdy',
        'Ruined',
        'Sadistic',
        'Sanctimonious',
        'Scheming',
        'Scornful',
        'Secretive',
        'Sedentary',
        'Selfish',
        'Self-indulgent',
        'Shallow',
        'Shortsighted',
        'Shy',
        'Silly',
        'Single-minded',
        'Sloppy',
        'Slow',
        'Sly',
        'Small-thinking',
        'Softheaded',
        'Sordid',
        'Steely',
        'Stiff',
        'Strong-willed',
        'Stupid',
        'Submissive',
        'Superficial',
        'Superstitious',
        'Suspicious',
        'Tactless',
        'Tasteless',
        'Tense',
        'Thievish',
        'Thoughtless',
        'Timid',
        'Transparent',
        'Treacherous',
        'Trendy',
        'Troublesome',
        'Unappreciative',
        'Uncaring',
        'Uncharitable',
        'Unconvincing',
        'Uncooperative',
        'Uncreative',
        'Uncritical',
        'Unctuous',
        'Undisciplined',
        'Unfriendly',
        'Ungrateful',
        'Unhealthy',
        'Unimaginative',
        'Unimpressive',
        'Unlovable',
        'Unpolished',
        'Unprincipled',
        'Unrealistic',
        'Unreflective',
        'Unreliable',
        'Unrestrained',
        'Unself-critical',
        'Unstable',
        'Vacuous',
        'Vague',
        'Venal',
        'Venomous',
        'Vindictive',
        'Vulnerable',
        'Weak',
        'Weak-willed',
        'Well-meaning',
        'Willful',
        'Wishful',
        'Zany',
        ],
};
let classObj = {
    'Artificer': ['Alchemist', 'Armorer', 'Artillerist', 'Battle Smith'],
    'Barbarian': ['Ancestral Guardian', 'Battlerager', 'Beast', 'Berserker', 'Storm Herald', 'Totem Warrior', 'Zealot', 'Wild Magic'],
    'Bard': ['Creation', 'Eloquence', 'Glamour', 'Lore', 'Spirits', 'Swords', 'Valor', 'Whispers'],
    'Cleric': ['Arcana', 'Death', 'Forge', 'Grave', 'Knowldege', 'Life', 'Light', 'Nature', 'Order', 'Peace', 'Tempest', 'Trickery', 'Twilight', 'War'],
    'Druid': ['Dreams', 'Spores', 'Stars', 'Wildfire', 'Land', 'Moon', 'Shepherd'],
    'Fighter': ['Arcane Archer', 'Battle Master', 'Cavalier', 'Champion', 'Echo Knight', 'Eldritch Knight', 'Psy Warrior', 'Banneret', 'Rune Knight', 'Samurai'],
    'Monk': ['Mercy', 'Shadow', 'Astral Self', 'Drunken Master', 'Four Elements', 'Kensei', 'Long Death', 'Open Hand', 'Sun Soul'],
    'Paladin': ['Conquest', 'Devotion', 'Glory', 'Redemption', 'Ancients', 'Crown', 'Watchers', 'Vengeance', 'Oathbreaker'],
    'Ranger': ['Beast Master', 'Fey Wanderer', 'Gloom Stalker', 'Horizon Walker', 'Hunter', 'Monster Slayer', 'Swarm Keeper'],
    'Rogue': ['Arcane Trickster', 'Assassin', 'Inquisitive', 'Phantom', 'Mastermind', 'Scout', 'Soul Knife', 'Swashbuckler', 'Thief'],
    'Sorceror': ['Aberrant Mind', 'Clockwork Soul', 'Divine Soul', 'Draconic Bloodline', 'Shadow Magic', 'Storm Sorcery', 'Wild Magic'],
    'Warlock': ['Archfey', 'Celestial', 'Fathomless', 'Fiend', 'Genie', 'Great Old One', 'Hexblade', 'Undead', 'Undying'],
    'Wizard': ['Bladesinging', 'Chronurgy', 'Graviturgy', 'Scribe', 'Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation', 'War Magic'],
};
let raceObj = {
    'Aarakocra': null, 
    'Aasimar': ['Fallen', 'Protector', 'Scourge', 'Variant'],
    'Bugbear': null,
    'Centaur': null,
    'Changeling': null,
    'Dragonborn': ['Draconblood', 'Ravenite'],
    'Dwarf': ['Duergar', 'Hill', 'Mountain'],
    'Elf': ['Aereni High', 'Aereni Wood', 'Drow', 'Eladrin', 'Variant Eladrin', 'High', 'Sea Elf', 'Shadar Kai', 'Valenar High', 'Valenar Wood', 'Wood'],
    'Firbolg': null,
    'Genasi': ['Air', 'Earth', 'Fire', 'Water'],
    'Gith': ['Githyanki', 'Githzerai'],
    'Gnome': ['Forest', 'Rock', 'Deep'],
    'Goliath': null,
    'Halfling': ['Ghostwise', 'Lightfoot', 'Lotusden', 'Stout'],
    'Half-Elf': ['Half-Aquatic', 'Half-Drow', 'Half-High', 'Half-Wood'],
    'Half-Orc': null,
    'Hobgoblin': null,
    'Human': ['Normal', 'Variant'],
    'Kalashtar': null,
    'Kenku': null,
    'Kobold': null,
    'Lizardfolk': null,
    'Loxodon': null,
    'Minotaur': null,
    'Orc': null,
    'Shifter': ['Beasthide', 'Longtooth', 'Swiftstride', 'Wildhunt'],
    'Simic Hybrid': null,
    'Tabaxi': null,
    'Tiefling': ['Asmodeus', 'Baalzebul', 'Dispater', 'Feral', 'Fierna', 'Glasya', 'Levistus', 'Mammon', 'Mephistopheles', 'Variant', 'Zariel'],
    'Tortle': null,
    'Triton': null,
    'Vedalken': null,
    'Warforged': null,
    'Yuan-Ti Pureblood': null
};
let nameObj = {
    'Aarakocra': [
        'Khu',
        'Krud',
        'Ek',
        'Ul',
        'Irk',
        'Uccarr',
        'Urarc',
        'Currerrk',
        'Ouccerr',
        'Accic'
        ], 
    'Aasimar': [
        'Elgim',
        'Crolam',
        'Raulrir',
        'Edreen',
        'Ydrin',
        'Olwont',
        'Airitar',
        'Iwunul',
        'Hawutint',
        'Weklanint'
        ],
    'Bugbear': [
        'Bridok',
        'Thitrimkk',
        'Ghevruth',
        'Zimkk',
        'Rak',
        'Hruttuk',
        'Stodunk',
        'Daggirk',
        'Netir',
        'Buttuth'
        ],
    'Centaur': [
        'Telzuthi Rivermuse',
        'Deldis Driftblossoms',
        "Zal'durd Hilltree",
        'Korlig Willowrise',
        'Kakle Plainvoice',
        'Taezukig Floodformer',
        'Ghal Willowgatherer',
        'Thendune Fogmind',
        "Vof'rir Springwish",
        'Thad Autumntwister'
        ],
    'Changeling': [
        'Wurx',
        'His',
        'Nurt',
        'Rouk',
        'Moots',
        'Eax',
        'Hag',
        'Vaez',
        'Ieks',
        'Lis'
        ],
    'Dragonborn': [
        'Lualthothujil Jardaar',
        'Nurashkmomash Xarwunax',
        'Myuaccik Nesvarax',
        'Croccash Durbor',
        'Shaxan Bhavroth',
        'Thiraxuak Pamash',
        'Murthashtish Morfras',
        'Precos Ghetrin',
        'Aalmistonduuth Vrakmorn',
        'Aphath Prikris'
        ],
    'Dwarf': [
        'Gwanwaen Stormale',
        'Lyesri Brawnshaper',
        'Brannys Battlebranch',
        'Lasra Truerest',
        'Dearla Hammerhead',
        'Nysnora Mamnack',
        'Bylleselle Bathgert',
        'Gwynnys Fobruholn',
        'Bonndielle Rongokin',
        'Bralras Cangeg'
        ],
    'Elf': [
        'Valhana Ambergrove',
        'Sylwynn Starfall',
        'Gilynore Oceanrest',
        'Quidi Hazelpride',
        'Nerilana Evendream',
        'Magmys Ashacostrie',
        'Uririe Dondroxos',
        'Keyrel Rulles',
        'Torsys Gollosh',
        'Liayra Ula'
        ],
    'Firbolg': [
        'Ilixidor Lunarspark',
        'Petsalor Silvermoon',
        'Erjeon Sagespirit',
        'Advalur Forestwatcher',
        'Perven Dawnheart',
        'Vaquinal Dithrostassinn',
        'Hernelis Hirithresh',
        'Kelris Altassa',
        'Miranan Fleme',
        'Norsandoral Veltasecath'
        ],
    'Genasi': [
    'Fiery',
    'Singe',
    'Shine',
    'Rill',
    'Puddle',
    'Paddle',
    'Geode',
    'Sandstone',
    'Soapstone',
    'Draft',
    'Storm',
    'Troposphere'
    ],
    'Gith': [
    'Xikon',
    "Da'anos",
    'Risin',
    'Deth',
    "R'a'as",
    "Tra'ac",
    'Arardac',
    "Tra'alas",
    'Vapath',
    "Jyd'i'th"
    ],
    'Gnome': [
    'Eniros Truebadge',
    'Panaben Luckycrag',
    'Yerug Strongtwist',
    'Farros Silverhide',
    'Horwor Twistbit',
    'Neshim Gaafiron',
    'Gani Pomban',
    'Corgrim Ripplelepple',
    'Zandon Ternaboren',
    'Kelfan Wipel'
    ],
    'Goliath': [
    'Pughan Lumberjumper Anakaligone',
    'Gearein Deerfriend Kolakavone',
    'Thavariak Hornchaser Lakumukane',
    'Taradath Flintdream Kulumigala',
    'Thavaziath Daymender Anakalithino',
    'Maphak Slyvigor Katho-Oliano',
    'Momak Thunderchaser Lakumileana',
    'Eaggal Hightwister Vuma-Thavi',
    'Augkin Daybearer Malukupine',
    'Pudath Masterherder Thulukena'
    ],
    'Halfling': [
    'Jobin Wisewhistle',
    'Danlan Tenman',
    'Osras Lonewood',
    'Zenyver Mistdancer',
    'Kasgin Cherrymouse',
    'Erret Grandbough',
    'Quinwrick Laughingcheeks',
    'Dankin Bronzebraid',
    'Fallan Hillspell',
    'Quoyas Nimblefeet'
    ],
    'Half-Elf': [
    'Traneiros',
    'Iandithas',
    'Nordithas',
    'Leotorin',
    'Faldithas',
    'Elstaer',
    'Yenreak',
    'Zanlumin',
    'Zylkas',
    'Rifaerd'
    ],
    'Half-Orc': [
    'Dororimm',
    'Kamagash',
    'Asirall',
    'Mugaruki',
    'Urog',
    'Trakarash',
    'Cagari',
    'Tanarth',
    'Zavurall',
    'Aggudash'
    ],
    'Hobgoblin': [
    'Dalvulorg',
    'Glakuc',
    'Dralvruk',
    'Drurdozun',
    'Glagralarg',
    'Rug Prowl',
    'Kleravod The Violent',
    'Klunkak The Corrupt',
    'Klekod The Violent',
    'Lerz Blow'
    ],
    'Human': [
    'Eishen Zakho',
    'Zushami Pene',
    'Brongim Sagebleeder',
    'Mie Sternshaper',
    'Glodami Rorsk',
    'Son Nimadz',
    'Lolcur Singlebringer',
    'Stethe Greenscribe',
    'Dunodur Fuuprinzat',
    'Teumen Dendib',
    'Roosvilder Troldintadzya',
    'Vlondisk Gravovo',
    'Lum Qiem',
    'Qie Yaing',
    'Grustubi Farguldal',
    'Hubai Cedrumel',
    ],
    'Kalashtar': [
    'Sinaulad',
    'Deskhad',
    'Nomelk',
    'Ghulad',
    'Khulad',
    'Dozia',
    'Bavoth',
    'Suva',
    'Chulril',
    'Cani'
    ],
    'Kenku': [
    'Paddler',
    'Jingler',
    'Flusher',
    'Hiccup',
    'Fox Yowl',
    'Ducker',
    'Panther Growl',
    'Book Slam',
    'Wood Drop',
    'Rope Slap'
    ],
    'Kobold': [
    'Zom',
    'Sun',
    'Dom',
    'Snov',
    'Oga',
    'Zikri',
    'Snirte',
    'Verpa',
    'Novlo',
    'Hukla'
    ],
    'Lizardfolk': [
    'Thre',
    'Ond',
    'Maltuass',
    'Laachord',
    'Medriask',
    'Argoth',
    'Rithre',
    'Lorhtustesh',
    'Ethrisres',
    'Ardekhy'
    ],
    'Loxodon': [
    'Seromi',
    'Zoondros',
    'Sis',
    'Bol',
    'Bralremoj',
    'Riz',
    'Svakozh',
    'Zal',
    'Svekool',
    'Choj'
    ],
    'Minotaur': [
    'Oestin Steadyfist',
    'Tinavera Vigilwarrior',
    'Denvin Gloryspeaker',
    'Vipen Thickrunner',
    'Neodera Stonehorn',
    'Jarnarun Bravespeaker',
    'Kintiran Heavyfighter',
    'Zarnarun Rockmind',
    'Jamaruk Sharpvigor',
    'Hunpiran Singlespeaker'
    ],
    'Orc': [
    'Bhub Pest Destroyer',
    'Juk The Deranged',
    'Bhab The Spiteful',
    'Dhag The Infernal',
    'Bodgag Ankle Flayer',
    'Dhokzak Flesh Ripper',
    'Ghabrok The Sick',
    'Ruzakk The Defiant',
    'Narzokk Sorrow Cleaver',
    'Rogzull Heel Ender'
    ],
    'Shifter': [
    'Spine',
    'Thistle',
    'Gust',
    'Flax',
    'Burst',
    'Vermin',
    'Magma',
    'Magna',
    'Tinder',
    'Vermin'
    ],
    'Simic Hybrid': [
    'Mulad',
    'Ghulad',
    'Davkosh',
    'Lomelk',
    'Moseulad',
    'Elafir',
    'Ralofaren',
    'Syljeon',
    'Zumnelis',
    'Pazumin'
    ],
    'Tabaxi': [
    'Rainbow After Rain (Rainbow)',
    'Sands of Time (Sand)',
    'Flow of the River (Flow)',
    'Tree Blossom (Blossom)',
    'Top Card (Card)',
    'Hearty Boat (Boat)',
    'Quick Stone (Quick)',
    'Sapphire Breath (Sapphire)',
    'Stout Grass (Grass)',
    'Violet Song (Song)'
    ],
    'Tiefling': [
    'Malmeros',
    'Dharxikas',
    'Akxire',
    'Ammos',
    'Mechar',
    'Horron',
    'Ekmeros',
    'Rerias',
    'Rolcis',
    'Ralmong'
    ],
    'Tortle': [
    'Dennott',
    'Taqweg',
    'Bek',
    'Krinyc',
    'Il',
    'Artla',
    'Diam',
    'Gum',
    'Yulill',
    'Xelan'
    ],
    'Triton': [
    'Doddos Junaxath',
    'Jhagas Uhnolnath',
    'Relzes Zarozath',
    'Dhilmis Guhnorath',
    'Jheges Modamnath',
    'Reves Uhmemath',
    'Mugus Ralallath',
    'Dalgas Munasnath',
    'Jhunlus Vomanzath',
    'Dunrus Bhahnodath'
    ],
    'Vedalken': [
    'Itluvatt',
    'Draldut',
    'Migun',
    'Avloz',
    'Koldullish',
    'Drordun',
    'Etlelluv',
    'Nhovroz',
    'Ziplullez',
    'Eran'
    ],
    'Warforged': [
    'Katana',
    'Caster',
    'Sprite',
    'Merger',
    'Officer',
    'Safeguard',
    'Beetle',
    'Glaive',
    'Scimitar',
    'Needle'
    ],
    'Yuan-Ti Pureblood': [
    'Ziskeess',
    'Otziush',
    'Sshastliul',
    'Ssotstluiss',
    'Zsohliu',
    'Yohliah',
    'Sezsihlih',
    'Talkeyuil',
    'Ssheskihli',
    'Zhohtlathi'
    ],
};	
let bgArr = [
    'Acolyte', 'Charlatan', 'Criminal', 'Entertainer', 'Folk Hero', 'Gladiator', 'Guild Artisan', 
    'Guild Merchant', 'Hermit', 'Knight', 'Noble', 'Outlander', 'Pirate', 'Sage', 'Sailor', 'Soldier', 'Spy', 'Urchin'
];

//VARIABLES
var Class = pickClass(classObj);
var subClass = pickSubClass(classObj);
var race = pickRace(raceObj);
var subRace = pickSubRace(raceObj);
var traitPos = pickTraitPos(traitObj);
var traitNeu = pickTraitNeu(traitObj);
var traitNeg = pickTraitNeg(traitObj);
var bg = pickBG(bgArr);
var stats = pickStats();
var nombre = pickName(nameObj);

//HTML HOOK
function getAll() {
    
    document.getElementById("randomResult").innerHTML = printRandom();

}

//FUNCTIONS 
function randomNum(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min + 1) + min);
}
function pickClass(classObj) {
    var randIndex = randomNum(0, Object.keys(classObj).length - 1);
    return Object.keys(classObj)[randIndex];
}
function pickSubClass(classObj) {
    var randIndex = randomNum(0, classObj[Class].length - 1);
    return classObj[Class][randIndex];
}
function pickRace(raceObj) {
    var randIndex = randomNum(0, Object.keys(raceObj).length - 1);
    return Object.keys(raceObj)[randIndex];
}
function pickSubRace(raceObj) {
    if (raceObj[race] === null) {
        return '-';
    } else {
        var randIndex = randomNum(0, raceObj[race].length - 1);
        return raceObj[race][randIndex];
    }
}
function pickTraitPos(traitObj) {
    var randIndex = randomNum(0, traitObj["Positive"].length - 1);
    return traitObj["Positive"][randIndex];
}
function pickTraitNeu(traitObj) {
    var randIndex = randomNum(0, traitObj["Neutral"].length - 1);
    return traitObj["Neutral"][randIndex];
}
function pickTraitNeg(traitObj) {
    var randIndex = randomNum(0, traitObj["Negative"].length - 1);
    return traitObj["Negative"][randIndex];
}
function pickBG(bgArr) {
    var randIndex = randomNum(0, bgArr.length - 1);
    return bgArr[randIndex];
}
function pickStats() {
    var resArr = [];
    var res = '';

    var d1 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd1 = 7;
    var d1Total = 0;
    for (var i = 0; i < d1.length; i++) {
        d1Total += d1[i];
        if (d1[i] < sd1) {
            sd1 = d1[i];
        }
    }
    d1Total -= sd1;
    resArr.push(d1Total);

    var d2 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd2 = 7;
    var d2Total = 0;
    for (var j = 0; j < d2.length; j++) {
        d2Total += d2[j];
        if (d2[j] < sd2) {
            sd2 = d2[j];
        }
    }
    d2Total -= sd2;
    resArr.push(d2Total);

    var d3 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd3 = 7;
    var d3Total = 0;
    for (var k = 0; k < d3.length; k++) {
        d3Total += d3[k];
        if (d3[k] < sd3) {
            sd3 = d3[k];
        }
    }
    d3Total -= sd3;
    resArr.push(d3Total);

    var d4 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd4 = 7;
    var d4Total = 0;
    for (var l = 0; l < d4.length; l++) {
        d4Total += d4[l];
        if (d4[l] < sd4) {
            sd4 = d4[l];
        }
    }
    d4Total -= sd4;
    resArr.push(d4Total);

    var d5 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd5 = 7;
    var d5Total = 0;
    for (var m = 0; m < d5.length; m++) {
        d5Total += d5[m];
        if (d5[m] < sd5) {
            sd5 = d5[m];
        }
    }
    d5Total -= sd5;
    resArr.push(d5Total);
    
    var d6 = [randomNum(1, 6), randomNum(1, 6), randomNum(1, 6), randomNum(1, 6)];
    var sd6 = 7;
    var d6Total = 0;
    for (var n = 0; n < d6.length; n++) {
        d6Total += d6[n];
        if (d6[n] < sd6) {
            sd6 = d6[n];
        }
    }
    d6Total -= sd6;
    resArr.push(d6Total);
    res = resArr.join('  /  ');
    return res;
}
function pickName(nameObj) {
    var randIndex = randomNum(0, nameObj[race].length - 1);
    return nameObj[race][randIndex];
}

//RESULT FUNCTION
function printRandom() {
    return `
    <em>Name:</em>   <b>${nombre}</b> <br><br>
    <em>Subrace:</em>   <b><a href='https://www.google.com/search?q=dnd+5e+${subRace}+subrace' target='_blank'>${subRace}</a></b> <br>
    <em>Race:</em>   <b><a href='https://www.google.com/search?q=dnd+5e+${race}' target='_blank'>${race}</a></b> <br><br>
    <em>Subclass:</em>   <b><a href='https://www.google.com/search?q=dnd+5e+${subClass}+${Class}' target='_blank'>${subClass}</a></b> <br>
    <em>Class:</em>   <b><a href='https://www.google.com/search?q=dnd+5e+${Class}' target='_blank'>${Class}</a></b> <br><br>
    <em>Background:</em>   <b><a href='https://www.google.com/search?q=dnd+5e+${bg}+background' target='_blank'>${bg}</a></b> <br><br>
    <em>Personality Traits:</em>   <b><a href='https://www.google.com/search?q=define+${traitPos}' target='_blank'> ${traitPos}</a>,
     <a href='https://www.google.com/search?q=define+${traitNeu}' target='_blank'>${traitNeu}</a>,
     <a href='https://www.google.com/search?q=define+${traitNeg}' target='_blank'> ${traitNeg}</a></b> <br><br>
    <em>Raw Ability Scores (4d6-Lowest):</em>   <b>${stats}</b> <br>
    `;
}

